// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViteAspire9.Api.Database;

#nullable disable

namespace ViteAspire9.Api.Migrations
{
    [DbContext(typeof(ResumeDbContext))]
    [Migration("20250205225049_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViteAspire9.Api.Database.ResumeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("ViteAspire9.Api.Database.ResumeEntity", b =>
                {
                    b.OwnsOne("ViteAspire9.Api.Database.ResumeDataEntity", "DataEntity", b1 =>
                        {
                            b1.Property<Guid>("ResumeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("ResumeEntityId");

                            b1.ToTable("Resumes");

                            b1.ToJson("DataEntity");

                            b1.WithOwner()
                                .HasForeignKey("ResumeEntityId");

                            b1.OwnsMany("ViteAspire9.Api.Database.EducationEntity", "Education", b2 =>
                                {
                                    b2.Property<Guid>("ResumeDataEntityResumeEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Degree")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.Property<DateTime?>("EndDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("School")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<DateTime>("StartDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("ResumeDataEntityResumeEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("Resumes");

                                    b2.WithOwner()
                                        .HasForeignKey("ResumeDataEntityResumeEntityId");
                                });

                            b1.OwnsMany("ViteAspire9.Api.Database.ExperienceEntity", "Experience", b2 =>
                                {
                                    b2.Property<Guid>("ResumeDataEntityResumeEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Company")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)");

                                    b2.Property<DateTime?>("EndDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("StartDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.HasKey("ResumeDataEntityResumeEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("Resumes");

                                    b2.WithOwner()
                                        .HasForeignKey("ResumeDataEntityResumeEntityId");
                                });

                            b1.Navigation("Education");

                            b1.Navigation("Experience");
                        });

                    b.Navigation("DataEntity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
